# Mac OS X Python build
language:
- objective-c
python:
- "2.7"
install:
# install python via brew
- brew install python
# make brews python the system default
- brew link --overwrite python
- which python
- python --version
# pip init
- pip install --upgrade pip
# final pip installs
- pip install -U git+https://github.com/metachris/py2app.git@master
- pip install git+https://github.com/jaredks/rumps.git
script:
  - python tests.py