language: python
sudo: required
python:
  - "2.7"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install -U git+https://github.com/metachris/py2app.git@master
script:
  - python tests.py
